### ISSUE TITLE
UnboundLocalError: local variable 'tag' referenced before assignment

### ISSUE THREAD

**Issue by kylebarron** [mcaceresb/tablefill#3] opened 2019-02-25 22:04 UTC
Just trying to create a simple example for the new RA... Am I doing something horribly stupid?

Using master:
```
> tablefill -i matrix.txt -o filled.tex template.tex
ERROR!
Traceback (most recent call last):
  File "/home/kyle/local/anaconda3/lib/python3.6/site-packages/tablefill/tablefill.py", line 337, in tablefill
    fill_engine.get_parsed_tables()
  File "/home/kyle/local/anaconda3/lib/python3.6/site-packages/tablefill/tablefill.py", line 793, in get_parsed_tables
    ctables[tag] += [clean_row_entries]
UnboundLocalError: local variable 'tag' referenced before assignment

ERROR while filling table. Check function call.

usage: tablefill.py [-h] [-v] [-i [INPUT [INPUT ...]]] [-o OUTPUT]
                    [-t {auto,lyx,tex}] [--pvals [PVALS [PVALS ...]]]
                    [--stars [STARS [STARS ...]]] [-f] [-c] [-b] [-fc]
                    [--ignore-xml] [--legacy-parsing] [--numpy-syntax]
                    [--use-floats] [--xml-tables [INPUT [INPUT ...]]]
                    [--verbose] [--silent]
                    TEMPLATE
```

`matrix.txt`:
```
example_matrix
         1	         2	         3
         3	       2.4	    2234.4
      1.32	     2.456	  3.345345
         3	       2.4	    2234.4
```

`template.tex`:
```latex
\documentclass{article}
\usepackage{tabularx}
\usepackage{booktabs}
\begin{document}
\begin{table}
  \caption{Table caption}
  \label{tab:example_matrix}
  \begin{tabular}{
  p{4.25cm}@{\hskip 6pt}c
  @{\hskip 15pt}
  r@{\hskip 3pt}c
  @{\hskip 15pt}
  c}
    Outcomes
    & N
    & Mean
    & (Std.)
    \\
    Outcomes 1 & \#0,\# & \#2,\# & (\#2,\#) \\
    Outcomes 2 & \#0,\# & \#2,\# & (\#2,\#) \\
    Outcomes 3 & \#0,\# & \#2,\# & (\#2,\#) \\
    Outcomes 4 & \#0,\# & \#2,\# & (\#2,\#) \\
    \multicolumn{4}{p{5cm}}{\footnotesize Footnotes here!}
  \end{tabular}
\end{table}
\end{document}
```

**Comment by mcaceresb** [comment] 2019-02-26 03:20
I think the tab regex is hard-coded. If you haven't customized it, then this should work:

```
<tab:example_matrix>
         1	         2	         3
         3	       2.4	    2234.4
      1.32	     2.456	  3.345345
         3	       2.4	    2234.4
```

I also think that it's supposed to be tab-delimited, not just arbitrary spaces.

**Comment by mcaceresb** [comment] 2019-02-26 03:22
I'm debating whether to invest time into documenting this project... I don't think it was obvious that this is the way the input file is supposed to be formatted Un...n

**Comment by kylebarron** [comment] 2019-02-26 15:01
I copy-pasted the matrix file, but it was created from `matrix_to_txt`, so it should have tabs in the file.

If you were interested in documenting the project I might be able to help a little. I still view the process as very complex, and I imagine a new RA would struggle with using it.

**Comment by mcaceresb** [comment] 2019-02-26 15:28
I was about to make a comment about how the process was not specially complex, but I think I'm underestimating how many steps are _actually_ involved...

1. Create a template using placeholders.
    - (Need to document placeholder system and such.)
    - Each table environment must be labeled as `\label{tab:tag}`
2. Export matrix from Stata to text file via `matrix_to_txt` with the analogous tag, `<tab:tag>`
    - The shape of the matrix must be the "shape" of the placeholders in the table environment.
    - (Need to document how missing values, etc. are handled and so on.
3. Run `tablefill -i matrix.txt -o filled.tex template.tex`
    - You can have multiple files with Stata matrices as input.
    - If there are tag conflicts then the last matrix with that tag is used.
    - (Need to document various tablefill options, including stars options when passing p-values)

**Comment by kylebarron** [comment] 2019-02-26 16:26
> I was about to make a comment about how the process was not specially complex, but I think I'm underestimating how many steps are _actually_ involved...

:laughing: 	Yes. It's a complex piece of software.

That said, I don't really know how to have flexible table output from Stata in any more simple way.

**Comment by mcaceresb** [comment] 2019-02-26 16:32
I really like this workflow, though. I actually think it's a very good idea (not so sure about my implementation). Whenever I share stuff through excel, for instance, I don't try to format stuff via Stata (which you can do, but is just painful). I pre-make a spreadsheet and export a matrix to fill in the numbers.

It's the same idea here and I think it's nice that you can have a LaTeX document with placeholders that you can see and format and work on, as opposed to having to deal with LaTeX formatting from Stata (which I have tried and is somewhat painful IMO).

Anyway, I haven't had to make LaTeX reports in a while, so it will be interesting to document this. I think I'll devote some time to it this weekend and put it up on readthedocs or gh-pages.

**Comment by kylebarron** [comment] 2019-02-26 16:39
My opinion would be great to also find tables in Markdown, but that's definitely some work and I'm done at this job in 4.5 weeks :open_mouth: 	

Also just saying that I love mkdocs :)

**Comment by michaelstepner** [comment] 2019-02-26 16:47
I know I'm off-topic from the original issue report, but just following along with the theme of documenting this package and how this workflow is really great...

You might want to add a reference to this package to Luke Stein's compilation of methods for generating tables in LaTeX from Stata: https://lukestein.github.io/stata-latex-workflows/

(Luke's tweet thread is here: https://twitter.com/lukestein/status/1097996795236372480)

**Comment by mcaceresb** [comment] 2019-02-26 17:07
@kylebarron I don't think it'd be that hard to fill markdown tables. What do you suggest to delimit the start and end of the table? Tags in the comments or something else?

I would be using mkdocs for this either way, it's just that the technicalities of how it's hosted (and the theme options!) are different. I really like the idea of having docs on a site dedicated to docs, but I am not a huge fan of RTD's themes...

@michaelstepner Totally agree this is a really nice  workflow, but Kyle is right that it's not entirely trivial to get started. I'm not really on twitter but I'll advocate for this workflow more once I actually document it!

**Comment by mcaceresb** [comment] 2019-02-27 03:20
I've put this on github pages [here](https://mcaceresb.github.io/tablefill/). It's mainly re-formatting stuff I'd already written, but it's incomplete. Happy to take pull requests on the docs. Not picky about keeping that format either, just something I threw together in the last 2 hrs.

**Comment by mcaceresb** [comment] 2019-02-27 12:58
@kylebarron This works now:

```
$ cat template.md 
<!-- tablefill:start tab:example_matrix -->

| Outcomes   | N    | Mean | (Std.) | 
| ---------- | ---- | ---- | ------ |
| Outcomes 1 | #0,# | #2,# | (#2,#) | 
| Outcomes 2 | #0,# | #2,# | (#2,#) | 
| Outcomes 3 | #0,# | #2,# | (#2,#) | 

<!-- tablefill:end -->
```

```
tablefill -i matrix.txt -o filled.md template.md
```

**Comment by kylebarron** [comment] 2019-02-27 14:54
Hey, I love `mkdocs-material` so I'm not about to suggest a change to the format  :)

Super cool about the Markdown. Does it still check for LaTeX tables as well in the Markdown document? At least when using Pandoc it's acceptable to have raw LaTeX in the Markdown document (those parts just won't be outputted when exporting to a non-LaTeX format).

**Comment by kylebarron** [comment] 2019-02-27 14:55
Apparently you have an errant link btw `/issues/2/tablefill.py` doesn't exist.
![image](https://user-images.githubusercontent.com/15164633/53499159-cc056100-3a75-11e9-8e0d-73d98b740f10.png)

**Comment by mcaceresb** [comment] 2019-02-27 15:12
A little hacky but now it does.

```
<!-- tablefill:start tab:example_matrix -->

| Outcomes   | N    | Mean | (Std.) |
| ---------- | ---- | ---- | ------ |
| Outcomes 1 | #0,# | #2,# | (#2,#) |
| Outcomes 2 | #0,# | #2,# | (#2,#) |
| Outcomes 3 | #0,# | #2,# | (#2,#) |

<!-- tablefill:end -->

\begin{table}
  \caption{Table caption}
  \label{tab:example_matrix}
  \begin{tabular}{p{4.25cm}crcc}
    Outcomes
    & N
    & Mean
    & (Std.)
    \
    Outcomes 1 & \#0,\# & \#2,\# & (\#2,\#) \
    Outcomes 2 & \#0,\# & \#2,\# & (\#2,\#) \
    Outcomes 3 & \#0,\# & \#2,\# & (\#2,\#) \
    Outcomes 4 & \#0,\# & \#2,\# & (\#2,\#) \
    \multicolumn{4}{p{5cm}}{\footnotesize Footnotes here!}
  \end{tabular}
\end{table}
```

gets filled correctly.

**Comment by mcaceresb** [comment] 2019-02-28 04:54
@kylebarron Can I close this? We're just iterating over the docs at this point.

**Comment by kylebarron** [comment] 2019-02-28 14:46
Let me try the original problem again. Since I'm not 100% sure it wasn't a bug in tablefill

**Comment by mcaceresb** [comment] 2019-02-28 14:48
Well, the label format is hard-coded. It has to be `<tab:...>`

I'm pretty sure modifying that would break something...

**Comment by kylebarron** [comment] 2019-02-28 14:50
ohhh I thought it was `tab:` in the latex file but didn't have to be in the matrix document

**Comment by mcaceresb** [comment] 2019-02-28 14:51
It has to be `<tab:...>` in the input because tablefill will look for _anything_ between labels, not just numbers (the original idea was that you could also replace text, which you can still do and I note that in the getting started now).

**Comment by kylebarron** [comment] 2019-02-28 14:53
Are you talking about small snippets of text? Like outside of tables?

**Comment by mcaceresb** [comment] 2019-02-28 14:59
Anywhere, right? `###` and `\#\#\#` will get replaced with a string.

```
<tab:some_label>
some text as long as it doesn't have any tabs...
```

**Comment by mcaceresb** [comment] 2019-02-28 15:02
Anyway, I updated the [getting started](https://mcaceresb.github.io/tablefill/getting-started.html) and I think the example there now is kind of cool. It includes this text-replacement thing and I added a placeholder construct to allow arbitrary python-style formatting.

Once there's a LyX example and the the advanced options get documented, I think the doc website will be pretty workable.

**Comment by mcaceresb** [comment] 2019-02-28 15:04
PS: There's a bug in the LaTeX code highlighting. If a comment is inside verbatim it's not suppose to gray out the entire line... Ah, well.

**Comment by pnystrup** [comment] 2019-04-08 18:23
@mcaceresb  I'm getting the same error as Kyle when I try to run the toy examples. Seems like it jumps straight to else and tries to access tag which isn't defined yet
```
for row in parse_data:
    if re.match(self.tags, row, flags = re.IGNORECASE):
        tag = re.findall(self.tags, row, flags = re.IGNORECASE)
        tag = tag[0].lower()
        ctables[tag] = []
    else:
        clean_row_entries = [e.strip() for e in row.split('\t')]
        ctables[tag] += [clean_row_entries]
```

**Comment by mcaceresb** [comment] 2019-04-08 18:26
In Kyle's case, he hadn't formatted the tag correctly. Could you post your toy example to make sure that's not the issue?

**Comment by pnystrup** [comment] 2019-04-08 18:32
Of course. The template is:

```
\documentclass{article}
\usepackage{tabularx}
\usepackage{booktabs}
\begin{document}
\begin{table}
  \caption{Table caption}
  \label{tab:example_matrix}
  \begin{tabular}{
  p{4.25cm}@{\hskip 6pt}c
  @{\hskip 15pt}
  r@{\hskip 3pt}c
  @{\hskip 15pt}
  c}
    Outcomes
    & N
    & Mean
    & (Std.)
    \\
    Outcomes 1 & \#0,\# & \#2,\# & (\#2,\#) \\
    Outcomes 2 & \#0,\# & \#2,\# & (\#2,\#) \\
    Outcomes 3 & \#0,\# & \#2,\# & (\#2,\#) \\
    Outcomes 4 & \#0,\# & \#2,\# & (\#2,\#) \\
    \multicolumn{4}{p{5cm}}{\footnotesize Footnotes here!}
  \end{tabular}
\end{table}
\end{document}
```

And the input is
```
<tab:example_matrix>
1	         2	         3

3	       2.4	    2234.4

1.32	     2.456	  3.345345

3	       2.4	    2234.4

<tab:example_raw>
1	         2	         3
3	       2.4	    2234.4
1.32	     2.456	  3.345345
3	       2.4	    2234.4
```

**Comment by mcaceresb** [comment] 2019-04-09 02:42
@pnystrup What are your tablefill and python versions? I couldn't reproduce the error. (For tablefill, you can type `tablefill -v`)

**Comment by pnystrup** [comment] 2019-04-09 05:29
@mcaceresb Tablefill 0.9.5, numpy 1.16.2, and Python 3.7.3 on Windows 10.

**Closed as completed** 2021-02-23 20:53 UTC
